### PR TITLE
Updated documentation and parameters to reflect current usage

### PR DESCRIPTION
**Pull request by lox**
In preparation of adding docker 1.8 and 1.9 targets, this clarifies usage for the current 1.6 target. 

This also removed ssh-agent support, as individual projects should handle authentication via environment variables.

### CODE REVIEW

**Comment by lox** [comment]
@toolmantim not sure how you guys would like to proceed in terms of pulling in changes, or whether I should be targeting these at the upstream repo.

**Comment by toolmantim** [comment]
Nar, I consider you the official maintainer, I would just push directly to buildkite/buildkite-aws-stack

**Comment by toolmantim** [comment]
I think you just merged to your master BTW… :)

**Comment by lox** [comment]
Yeah, I figured it was already here and working. I'm merge into the buildkite master when stable.

**Pull request merged**
